version: '3.8'

services:

  postgres:
    image: postgres:14
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", 'pg_isready -U "$$POSTGRES_USER"' ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./local/postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.9.16-management
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 60s
      timeout: 10s
      retries: 5
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq

  kira:
    build: .
    tty: true
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      KIRA_DB_HOST: postgres
      KIRA_DB_PORT: 5432
      KIRA_DB_DATABASE: postgres
      KIRA_DB_USER: postgres
      KIRA_DB_PASSWORD: postgres

      KIRA_RABBIT_USER: rabbitmq
      KIRA_RABBIT_PASSWORD: rabbitmq
      KIRA_RABBIT_HOST: rabbitmq
      KIRA_RABBIT_PORT: 5672
    env_file:
      - private.env
    volumes:
      - ./config.json:/app/config.json
